code --install-extension aaron-bond.better-comments
code --install-extension adam-watters.vscode-color-pick
code --install-extension ahmadawais.shades-of-purple
code --install-extension alefragnani.Bookmarks
code --install-extension bierner.emojisense
code --install-extension BurntBanana.checkpoint
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cymonk.sql-formatter
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension DeepInThought.vscode-shell-snippets
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension erd0s.terraform-autocomplete
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.shell-format
code --install-extension ginfuru.ginfuru-vscode-jekyll-syntax
code --install-extension ginfuru.vscode-jekyll-snippets
code --install-extension Gruntfuggly.todo-tree
code --install-extension hashicorp.terraform
code --install-extension hediet.vscode-drawio
code --install-extension himanoa.Python-autopep8
code --install-extension humao.rest-client
code --install-extension jeff-hykin.polacode-2019
code --install-extension mechatroner.rainbow-csv
code --install-extension micnil.vscode-checkpoints
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.anaconda-extension-pack
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vscode.wordcount
code --install-extension mtxr.sqltools
code --install-extension naumovs.color-highlight
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension purocean.drawio-preview
code --install-extension qezhu.gitlink
code --install-extension RandomFractalsInc.vscode-data-preview
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension RoscoP.ActiveFileInStatusBar
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-portuguese
code --install-extension streetsidesoftware.code-spell-checker-portuguese-brazilian
code --install-extension timonwong.shellcheck
code --install-extension tomoki1207.pdf
code --install-extension truman.autocomplate-shell
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension WakaTime.vscode-wakatime
code --install-extension wingrunr21.vscode-ruby
code --install-extension yzane.markdown-pdf
