code --install-extension adpyke.vscode-sql-formatter
code --install-extension donjayamanne.githistory
code --install-extension dvirtz.parquet-viewer
code --install-extension eamodio.gitlens
code --install-extension finitewisdom.identifize
code --install-extension fnando.linter
code --install-extension mechatroner.rainbow-csv
code --install-extension mrrefactoring.polacode-fixed-edition
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-pt-BR
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension phplasma.csv-to-table
code --install-extension WakaTime.vscode-wakatime
